version: '3.8'

services:
  server:
    build: ./server
    container_name: flask-server
    env_file: ./server/.env
    volumes:
      - ./server:/app
    ports:
      - "5001:5000"
    depends_on:
      - db

  client:
    build: ./client
    container_name: react-client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:3000"

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: seifeddine
      POSTGRES_DB: sportlink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
