version: '3.8'

services:
  server:
    build: ./server
    container_name: flask-server
    env_file: ./server/.env  # Load the environment variables from the .env file
    volumes:
      - ./server:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
    # No need to specify the environment variables again since they are loaded from .env

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: seifeddine
      POSTGRES_DB: sportlink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
